# Analisis de sentimientos
Es el proceso automatizado de etiquetar datos de acuerdo al sentimiento del texto como: positivo, negativo, neutro. Es usado en compañías para detectar nuevas percepciones y conocimientos de datos en escala. En su esencia es lenguaje natural de procesamiento, una técnica para clasificar la polaridad de texto segun su sentimiento.

Permite el procesamiento de datos en escala y tiempo real, se puede automatizar esta clasificación para entender directamente como las personas hablan y opinan acerca de un tema en específico, lo que permite a organizaciones:
- Tomar acciones basada en el conocimiento adquerido a partir de los datos.
- Entender como las personas estan hablando de una marca vs competidores 
- Analizar comentarios de encuestas y reseñas de productos 
- Analizar solicitudes o reportes de errores en servicios (tickets) para evitar tasa de cancelación (churn)

# Comandos relevantes para el proyecto en la terminal:
### Instalación y configuración

In [ ]:
# En la terminal con el env. ya creado, versión usada para este proyecto python=3.11
#(sentiment_analysis)  > conda env export --no-builds > environment.yml 
#(sentiment_analysis)  > 
#(sentiment_analysis)  > conda install -c conda-forge transformers
# Instalar
#(sentiment_analysis)  > conda install -c conda-forge ipykernel
# Registrar
#(sentiment_analysis)  > python -m ipykernel install --user --name mi_entorno --display-name "Python (mi_entorno)" 
#CPU
#(sentiment_analysis)  > conda install pytorch torchvision torchaudio cpuonly -c pytorch
#GPU
#(sentiment_analysis)  > conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
# Forge
#(sentiment_analysis)  > conda install -c conda-forge ipywidgets pandas

In [3]:
import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer as sia
import matplotlib.pyplot as plt
from deep_translator import GoogleTranslator as ggt
import seaborn as sns
from wordcloud import WordCloud as wc
from textblob import TextBlob
import spacy  
from transformers import pipeline
import pyodbc

In [6]:
#import torch
#import transformers
#print(torch.__version__)
#print(transformers.__version__)

conexion = pyodbc.connect(
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=localhost;"
    "DATABASE=sentiment_analysis_db;"
    "Trusted_Connection=yes;"    
    "TrustServerCertificate=yes;"
)

df_sql = pd.read_sql("SELECT * FROM comentarios;",conexion)

conexion.close()

print(df_sql.shape)
print(df_sql.head())

with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.max_colwidth', None): 
    display(df_sql)

(203, 4)
   id                                              texto  sentimiento  \
0   1  Excelente atención y muy buena disposición en ...          1.0
1   2  Los productos son de alta calidad y siempre ll...          1.0
2   3  Me encanta el diseño y la funcionalidad de la ...          1.0
3   4  Estoy muy contento con el producto, superó mis...          1.0
4   5  El servicio postventa fue excelente, resolvier...          1.0

   categoria
0          1
1          1
2          1
3          1
4          1

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_17396\3856022461.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_sql = pd.read_sql("SELECT * FROM comentarios;",conexion)

,id,texto,sentimiento,categoria
0,1,Excelente atención y muy buena disposición en el servicio. Recomendado.,1.0,1
1,2,Los productos son de alta calidad y siempre llegan a tiempo. Muy satisfecho.,1.0,1
2,3,Me encanta el diseño y la funcionalidad de la aplicación. Es intuitiva y fácil de usar.,1.0,1
3,4,"Estoy muy contento con el producto, superó mis expectativas en todos los sentidos.",1.0,1
4,5,"El servicio postventa fue excelente, resolvieron mi problema de inmediato.",1.0,1
5,6,"Muy mala experiencia con la compra, el producto llegó en mal estado.",0.0,1
6,7,El servicio al cliente fue poco profesional y no resolvieron mis problemas.,0.0,1
7,8,"Me siento decepcionado, la calidad no es como la prometen en la publicidad.",0.0,1
8,9,Tardaron demasiado en responder y no solucionaron mi inconveniente.,0.0,1
9,10,"No recomendaría este servicio, tuve problemas desde el principio.",0.0,1
10,11,"La exposición de arte fue increíble, muy bien organizada y con grandes obras.",1.0,2
11,12,"El evento cultural superó mis expectativas, hubo mucho talento en cada presentación.",1.0,2
12,13,El museo cuenta con exhibiciones interactivas y muy educativas. Ideal para la familia.,1.0,2
13,14,"La programación del festival fue variada y atractiva, disfruté cada actividad.",1.0,2
14,15,"Asistir al concierto fue una experiencia única, la música y el ambiente fueron excelentes.",1.0,2
15,16,"El evento cultural fue una decepción, estuvo mal organizado y el audio fue terrible.",0.0,2
16,17,"La exposición no fue interesante, muy pocas piezas y mala distribución.",0.0,2
17,18,El museo no tiene muchas actividades y es bastante aburrido.,0.0,2
18,19,"No disfruté el festival, la programación fue monótona y poco atractiva.",0.0,2
19,20,"La calidad de las presentaciones fue baja, esperaba mucho más.",0.0,2
20,21,"El nuevo programa educativo es excelente, los estudiantes están motivados.",1.0,3
21,22,Las clases interactivas han aumentado el interés de los alumnos en aprender.,1.0,3
22,23,La plataforma educativa es muy completa y fácil de usar.,1.0,3
23,24,Las actividades extracurriculares complementan muy bien la educación formal.,1.0,3
24,25,"El colegio ha mejorado sus instalaciones, es un ambiente cómodo y moderno.",1.0,3
25,26,"Las instalaciones de la escuela están en pésimas condiciones, requieren mantenimiento urgente.",0.0,3
26,27,Falta de recursos en el colegio afecta la calidad de la educación.,0.0,3
27,28,La plataforma educativa es lenta y difícil de navegar.,0.0,3
28,29,Los estudiantes no reciben suficiente apoyo en sus estudios.,0.0,3
29,30,El material de estudio está desactualizado y es poco útil.,0.0,3
30,31,"Me encantó el servicio que recibí, realmente excelente.",1.0,1
31,32,"El producto superó mis expectativas, muy recomendado.",1.0,1
32,33,Todo el proceso de compra fue rápido y eficiente.,1.0,1
33,34,El equipo de atención al cliente fue muy amable.,1.0,1
34,35,La entrega fue puntual y el producto llegó en buen estado.,1.0,1
35,36,El servicio al cliente fue pésimo y no resolvió mi problema.,0.0,1
36,37,No estoy satisfecho con la calidad del producto.,0.0,1
37,38,El proceso de compra fue confuso y lento.,0.0,1
38,39,La entrega tardó mucho más de lo esperado.,0.0,1
39,40,El producto llegó dañado y no cumplen con el reemplazo.,0.0,1
40,41,La exposición de arte fue inspiradora y bien organizada.,1.0,2
41,42,El museo cuenta con una colección impresionante.,1.0,2
42,43,El evento cultural fue enriquecedor y entretenido.,1.0,2
43,44,La obra de teatro superó todas mis expectativas.,1.0,2
44,45,La feria cultural mostró una gran diversidad de tradiciones.,1.0,2
45,46,La exposición estaba desordenada y sin organización.,0.0,2
46,47,El museo estaba vacío y sin actividades interesantes.,0.0,2
47,48,El evento cultural fue aburrido y sin nada especial.,0.0,2
48,49,La obra de teatro careció de emoción y profesionalismo.,0.0,2
49,50,La feria cultural fue decepcionante y sin variedad.,0.0,2
50,51,El curso en línea fue muy completo y bien estructurado.,1.0,3
51,52,Los profesores están muy capacitados y comprometidos.,1.0,3
52,53,La plataforma educativa es fácil de usar y completa.,1.0,3
53,54,Las clases en línea me ayudaron a mejorar mis habilidades.,1.0,3
54,55,El ambiente de aprendizaje es muy estimulante.,1.0,3
55,56,El curso en línea fue confuso y mal estructurado.,0.0,3
56,57,Los profesores no respondieron mis dudas.,0.0,3
57,58,La plataforma educativa es difícil de navegar.,0.0,3
58,59,Las clases en línea no cumplieron mis expectativas.,0.0,3
59,60,El ambiente de aprendizaje es desmotivador.,0.0,3
60,61,"La experiencia en este restaurante fue realmente excepcional, el ambiente acogedor y la comida deliciosa hicieron de nuestra velada una ocasión especial.",1.0,1
61,62,"Estoy muy satisfecho con el servicio al cliente de esta empresa, resolvieron todas mis dudas con rapidez y amabilidad, es difícil encontrar atención así.",1.0,1
62,63,"La última actualización de la aplicación ha mejorado muchísimo su rendimiento, ahora es rápida, intuitiva y muy fácil de usar, la recomiendo totalmente.",1.0,1
63,64,"La calidad de los productos que compré superó mis expectativas, no solo son duraderos sino también estéticamente agradables, una compra excelente.",1.0,1
64,65,"La película que vi el fin de semana fue impresionante, la trama estaba bien desarrollada y los efectos visuales eran espectaculares, me dejó sin palabras.",1.0,1
65,66,"Lamentablemente, la atención en el restaurante dejó mucho que desear, el servicio fue lento y la comida llegó fría, no pienso regresar.",0.0,1
66,67,"Tuve una experiencia bastante negativa con el servicio técnico, no lograron solucionar mi problema y solo generaron más confusión.",0.0,1
67,68,"El producto que adquirí se dañó al poco tiempo de uso y el servicio postventa no me brindó ninguna solución, muy decepcionante.",0.0,1
68,69,"La aplicación es extremadamente lenta y difícil de navegar, cada vez que la uso siento que pierdo más tiempo del que ahorro.",0.0,1
69,70,"La película que vi fue una pérdida de tiempo, el guion era predecible y las actuaciones nada convincentes, no la recomiendo.",0.0,1
70,71,"La exposición de arte moderno en el museo fue maravillosa, cada obra estaba llena de vida y creatividad, un deleite para los amantes del arte.",1.0,2
71,72,"El concierto de la orquesta sinfónica fue una experiencia impresionante, cada pieza interpretada con una pasión que llegaba al alma, lo disfruté mucho.",1.0,2
72,73,"La festividad cultural de este año fue realmente asombrosa, las tradiciones, bailes y muestras gastronómicas representaron fielmente nuestra herencia.",1.0,2
73,74,"El documental que vi sobre las antiguas civilizaciones fue fascinante, muy bien investigado y con imágenes impactantes, muy recomendable.",1.0,2
74,75,"La visita guiada al sitio arqueológico fue educativa y emocionante, el guía explicaba cada detalle con gran entusiasmo y conocimiento.",1.0,2
75,76,"El festival cultural de este año fue bastante decepcionante, la organización fue deficiente y las actividades parecían improvisadas.",0.0,2
76,77,"Visité el museo pero muchas de las exhibiciones estaban cerradas, lo cual fue frustrante, especialmente después de pagar la entrada completa.",0.0,2
77,78,"La obra de teatro no fue lo que esperaba, el guion carecía de cohesión y las actuaciones no lograron conectar con el público.",0.0,2
78,79,"El concierto fue una experiencia incómoda debido al mal sonido, apenas se podían entender las letras de las canciones.",0.0,2
79,80,"La exposición de arte contemporáneo no fue de mi gusto, parecía falta de creatividad y sin un tema claro, me dejó insatisfecho.",0.0,2
80,81,"La nueva metodología de enseñanza ha logrado que los estudiantes participen más y disfruten del proceso de aprendizaje, es un cambio notable.",1.0,3
81,82,"Estoy impresionado con la calidad de los recursos educativos disponibles en línea, hacen que el aprendizaje sea accesible y práctico.",1.0,3
82,83,"La universidad ha implementado programas de tutoría que han sido muy útiles para los alumnos, han ayudado mucho en su desarrollo académico.",1.0,3
83,84,"La conferencia educativa a la que asistí fue inspiradora, los ponentes eran expertos en su área y brindaron conocimientos muy valiosos.",1.0,3
84,85,La escuela ha realizado mejoras en sus instalaciones y se nota que los estudiantes están más cómodos y enfocados en sus estudios.,1.0,3
85,86,"El material educativo está desactualizado y no refleja los avances recientes en la materia, los estudiantes no están aprendiendo lo necesario.",0.0,3
86,87,"La plataforma de aprendizaje en línea es confusa y difícil de usar, paso más tiempo tratando de entenderla que aprendiendo realmente.",0.0,3
87,88,"Los recursos para la clase son limitados y muchas veces no están disponibles cuando los necesitamos, lo que afecta el proceso de aprendizaje.",0.0,3
88,89,"El nivel de los profesores en algunos cursos deja mucho que desear, no están preparados para enseñar y eso se refleja en el desempeño de los alumnos.",0.0,3
89,90,"Las condiciones de la escuela son bastante deficientes, hay falta de infraestructura adecuada para llevar a cabo las clases correctamente.",0.0,3
90,91,"La experiencia en este restaurante fue realmente excepcional, un verdadero mosaico de sabores que deleitó cada sentido; el ambiente acogedor y los victuals deliciosos orquestaron una velada inolvidable.",1.0,1
91,92,"Estoy muy satisfecho con el servicio al cliente de esta empresa; los empleados se encargaron de cada detalle con amabilidad y rapidez, reimaginando lo que uno espera de una atención al cliente.",1.0,1
92,93,"La última actualización de la aplicación fue un éxito, repleta de mejoras que la hicieron más rápida y fácil de navegar, facilitando una experiencia verdaderamente enriquecedora",1.0,1
93,94,"La calidad de los productos que adquirí superó todas mis expectativas, construidos con atención y durabilidad, se destacan tanto en diseño como en funcionalidad, un verdadero hallazgo.",1.0,1
94,95,"La película que vi el fin de semana fue un crucible de emociones, con una trama intrincada y efectos visuales cautivadores; ciertamente la recomendaría a cualquier amante del buen cine.",1.0,1
95,96,"Lamentablemente, la atención en el restaurante fue un laberinto de problemas, desde el servicio lento hasta la comida fría, fue una experiencia que no deseo repetir.",0.0,1
96,97,"Mi interacción con el servicio técnico dejó mucho que desear; en lugar de ayudar, solo aumentaron la confusión y el problema inicial, sumergiéndome en una frustrante experiencia.",0.0,1
97,98,"El producto que compré se deshizo al poco tiempo de uso, una decepción que el servicio postventa no mejoró; en lugar de una solución, recibí excusas.",0.0,1
98,99,"El producto que compré se deshizo al poco tiempo de uso, una decepción que el servicio postventa no mejoró; en lugar de una solución, recibí excusas.",0.0,1
99,100,"La película fue una verdadera pérdida de tiempo, con un guion predecible y actuaciones sin vida; la falta de calidad ciertamente fue evidente.",0.0,1
100,101,"La muestra de arte contemporáneo superó todas mis expectativas, los colores vibrantes y las temáticas sociales transmitían un mensaje profundo y emotivo.",1.0,2
101,102,"El festival de danza cultural fue increíble, cada actuación reflejaba una riqueza y diversidad cultural que emocionó a todos los asistentes.",1.0,2
102,103,"El evento de intercambio cultural permitió conocer costumbres y tradiciones de diferentes países, creando un ambiente de aprendizaje y respeto mutuo.",1.0,2
103,104,"La película histórica que vi recientemente estaba muy bien documentada, los detalles y la ambientación transportaban al espectador a otra época.",1.0,2
104,105,"El taller de cerámica ancestral me permitió aprender técnicas artesanales milenarias, apreciando aún más el valor del arte tradicional.",1.0,2
105,106,"El festival cultural fue bastante decepcionante, las actividades no tenían cohesión y parecía que faltaba organización en todo momento.",0.0,2
106,107,"La exposición de esculturas modernas me dejó indiferente, no logré conectar con el estilo y la falta de contexto de algunas obras.",0.0,2
107,108,"El evento prometía una experiencia cultural completa, pero resultó ser una presentación monótona sin ningún valor añadido para el público.",0.0,2
108,109,"Asistí a una obra de teatro que, aunque tenía un guion interesante, la actuación fue tan plana que se perdió todo el dramatismo de la historia.",0.0,2
109,110,"El museo tenía pocas exposiciones abiertas y la mayoría estaban en malas condiciones, fue una experiencia frustrante para los visitantes.",0.0,2
110,111,"La nueva plataforma educativa ha facilitado muchísimo el aprendizaje, permite acceder a contenido didáctico de alta calidad en cualquier momento del día.",1.0,3
111,112,"El programa de tutorías personalizadas ha sido fundamental para mejorar el rendimiento académico de muchos estudiantes, se sienten más seguros y motivados.",1.0,3
112,113,La reciente inversión en laboratorios escolares ha permitido que los alumnos puedan experimentar y aprender de manera práctica en un entorno seguro.,1.0,3
113,114,"La biblioteca digital de la universidad ofrece un amplio acceso a artículos, libros y tesis que enriquecen el proceso educativo de manera notable.",1.0,3
114,115,La implementación de métodos de enseñanza interactivos ha logrado captar el interés de los estudiantes y hacer del aprendizaje una experiencia agradable.,1.0,3
115,116,"El material de estudio proporcionado está desactualizado y ya no es útil para los temas actuales, los estudiantes no logran profundizar en su aprendizaje.",0.0,3
116,117,"La plataforma en línea para las clases virtuales es complicada y suele fallar, lo que genera frustración en los estudiantes y afecta el flujo de la clase.",0.0,3
117,118,Los recursos de aprendizaje son insuficientes y en muchas ocasiones los estudiantes no tienen acceso a lo que necesitan para hacer sus tareas.,0.0,3
118,119,"El método de enseñanza en algunos cursos es obsoleto, los estudiantes pierden interés porque no encuentran relevancia en lo que están aprendiendo.",0.0,3
119,120,"Las instalaciones del colegio están en malas condiciones, lo que da una mala imagen y afecta la comodidad y seguridad de los estudiantes.",0.0,3
120,121,Lo pasamos muy bien en nuestra salida.,1.0,1
121,122,Nuestra cita fue muy agradable.,1.0,1
122,123,Me gusta mucho este tipo de helado.,1.0,1
123,124,Siento que mejoran cada vez más en calidad de sus productos.,1.0,1
124,125,Esa felicula fue fantastica.,1.0,1
125,126,Estoy muy decepcionado por como me trataron.,0.0,1
126,127,Me hiciseron sentir super mal.,0.0,1
127,128,Lo pasamos horrible en aquella salida.,0.0,1
128,129,"No quiero voler a salir con ellos, estuvo muy aburrido.",0.0,1
129,130,En mi opinion está muy mal lo que hizo ella.,0.0,1
130,131,"La exposición de arte moderno en el museo fue maravillosa, cada obra estaba llena de vida y creatividad, un deleite para los amantes del arte.",1.0,2
131,132,"El concierto de la orquesta sinfónica fue una experiencia impresionante, cada pieza interpretada con una pasión que llegaba al alma, lo disfruté mucho.",1.0,2
132,133,"La festividad cultural de este año fue realmente asombrosa, las tradiciones, bailes y muestras gastronómicas representaron fielmente nuestra herencia.",1.0,2
133,134,"El documental que vi sobre las antiguas civilizaciones fue fascinante, muy bien investigado y con imágenes impactantes, muy recomendable.",1.0,2
134,135,"La visita guiada al sitio arqueológico fue educativa y emocionante, el guía explicaba cada detalle con gran entusiasmo y conocimiento.",1.0,2
135,136,"El festival cultural de este año fue bastante decepcionante, la organización fue deficiente y las actividades parecían improvisadas.",0.0,2
136,137,"Visité el museo pero muchas de las exhibiciones estaban cerradas, lo cual fue frustrante, especialmente después de pagar la entrada completa.",0.0,2
137,138,"La obra de teatro no fue lo que esperaba, el guion carecía de cohesión y las actuaciones no lograron conectar con el público.",0.0,2
138,139,"El concierto fue una experiencia incómoda debido al mal sonido, apenas se podían entender las letras de las canciones.",0.0,2
139,140,"La exposición de arte contemporáneo no fue de mi gusto, parecía falta de creatividad y sin un tema claro, me dejó insatisfecho.",0.0,2
140,141,"La nueva metodología de enseñanza ha logrado que los estudiantes participen más y disfruten del proceso de aprendizaje, es un cambio notable.",1.0,3
141,142,"Estoy impresionado con la calidad de los recursos educativos disponibles en línea, hacen que el aprendizaje sea accesible y práctico.",1.0,3
142,143,"La universidad ha implementado programas de tutoría que han sido muy útiles para los alumnos, han ayudado mucho en su desarrollo académico.",1.0,3
143,144,"La conferencia educativa a la que asistí fue inspiradora, los ponentes eran expertos en su área y brindaron conocimientos muy valiosos.",1.0,3
144,145,La escuela ha realizado mejoras en sus instalaciones y se nota que los estudiantes están más cómodos y enfocados en sus estudios.,1.0,3
145,146,"El material educativo está desactualizado y no refleja los avances recientes en la materia, los estudiantes no están aprendiendo lo necesario.",0.0,3
146,147,"La plataforma de aprendizaje en línea es confusa y difícil de usar, paso más tiempo tratando de entenderla que aprendiendo realmente.",0.0,3
147,148,"Los recursos para la clase son limitados y muchas veces no están disponibles cuando los necesitamos, lo que afecta el proceso de aprendizaje.",0.0,3
148,149,"El nivel de los profesores en algunos cursos deja mucho que desear, no están preparados para enseñar y eso se refleja en el desempeño de los alumnos.",0.0,3
149,150,"Las condiciones de la escuela son bastante deficientes, hay falta de infraestructura adecuada para llevar a cabo las clases correctamente.",0.0,3
150,151,"La atención en la tienda fue excepcional, el personal fue muy amable y servicial.",1.0,1
151,152,"El libro que leí recientemente me inspiró profundamente, no podía dejar de pensar en sus enseñanzas.",1.0,1
152,153,"La clase de yoga que tomé fue revitalizante, el instructor fue muy profesional y atento.",1.0,1
153,154,"La decoración de la habitación del hotel era encantadora, me sentí como en casa.",1.0,1
154,155,"Disfruté mucho del viaje, los paisajes eran impresionantes y la gente muy acogedora.",1.0,1
155,156,La comida en el restaurante estaba insípida y no cumplió con mis expectativas.,0.0,1
156,157,"El servicio al cliente fue deficiente, no respondieron mis correos y me sentí ignorado.",0.0,1
157,158,"La última actualización de la aplicación trajo más problemas que soluciones, es frustrante.",0.0,1
158,159,"La calidad de los zapatos que compré fue muy baja, se rompieron en poco tiempo.",0.0,1
159,160,"La película que vi fue un verdadero fiasco, no logró captar mi interés en ningún momento.",0.0,1
160,161,"La conferencia sobre historia antigua fue muy interesante, el conferenciante tenía un gran conocimiento sobre el tema.",1.0,2
161,162,"El festival de música folclórica fue una verdadera celebración de nuestras raíces, con música y bailes tradicionales hermosos.",1.0,2
162,163,"La visita al museo de historia natural fue una experiencia emocionante, con exposiciones interactivas y bien explicadas.",1.0,2
163,164,"El libro que leí sobre la cultura japonesa fue fascinante, me dio una nueva perspectiva sobre su forma de vida.",1.0,2
164,165,"La exposición de fotografía de viajes fue inspiradora, con imágenes impresionantes de diferentes partes del mundo.",1.0,2
165,166,"La exposición de arte moderno fue confusa y sin sentido, con obras que no tenían una conexión clara entre ellas.",0.0,2
166,167,"El concierto de música clásica fue una decepción, con un mal sonido y artistas que no estaban a la altura de las expectativivas.",0.0,2
167,168,"La visita al museo de historia fue decepcionante, con exposiciones anticuadas y sin una actualización en muchos años.",0.0,2

In [9]:
filas = []

#Limpieza
# Se utiliza "latin-1" debido a que el archivo posee caracteres como tildes (á, é etc) o la letra eñe (ñ) que el tradicional utf-8 no soporta 
with open('comentarios.csv',encoding='latin1' ) as f:   # with: Context manager, cerrar el archivo 
    header = next(f)         # Salta header (primera columna de f)
    
    for linea in f:
        # .strip -> elimina espacios blanco y \n  
        linea = linea.strip()

        if linea.startswith('"'):
            linea = linea.strip(',')
            linea = linea.strip('"')
        else:
            linea = linea.strip(',')

        parte_linea = linea.split(';')      #.split(';') separa en pedazos
        texto = ';'.join(parte_linea[:-2])          # parte_linea[:-2] desde el inicio hasta el penultimo elemento, todo excepto los ultimos 2 elementos
        #texto = ';'
        sentimiento = parte_linea[-2].strip()
        categoria = parte_linea[-1].strip()
        filas.append([texto,sentimiento,categoria])

comentarios = pd.DataFrame(filas, columns=['texto', 'sentimiento', 'categoria'])
comentarios['sentimiento'] = pd.to_numeric(comentarios['sentimiento'], errors='coerce') # default error raise -> Exception 
comentarios['categoria']   = pd.to_numeric(comentarios['categoria'],   errors='coerce') # Invalid converts into Nan

#comentarios


#with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.max_colwidth', None): 
#    display(comentarios)

comentarios.to_csv('comentarios_limpio.csv',index=True, encoding='utf-8-sig',sep='|' )

In [22]:
traductor = ggt(source='auto',target='en')

polaridad = []
subjetividad = []
sentimiento_tb = []

for texto in comentarios['texto']:
    traduccion = traductor.translate(texto)

    blob = TextBlob(traduccion)
    pol = blob.sentiment.polarity
    sub = blob.sentiment.subjectivity

    if pol > 0:
        etiqueta = "Positivo"
    elif pol < 0:
        etiqueta = "Negativo"
    else:
        etiqueta = "Neutro"
    
    polaridad.append(pol)
    subjetividad.append(sub)
    sentimiento_tb.append(etiqueta)

comentarios['tb_polaridad'] = polaridad
comentarios['tb_subjetividad'] = subjetividad
comentarios['tb_sentimiento'] = sentimiento_tb

comentarios.head(10)

,texto,sentimiento,categoria,tb_polaridad,tb_subjetividad,tb_sentimiento
0,Excelente atención y muy buena disposición en ...,1,1,0.955000,0.890000,Positivo
1,Los productos son de alta calidad y siempre ll...,1,1,0.405000,0.770000,Positivo
2,Me encanta el diseño y la funcionalidad de la ...,1,1,0.466667,0.716667,Positivo
3,"Estoy muy contento con el producto, superó mis...",1,1,1.000000,1.000000,Positivo
4,"El servicio postventa fue excelente, resolvier...",1,1,1.000000,1.000000,Positivo
5,"Muy mala experiencia con la compra, el product...",0,1,-0.655000,0.733333,Negativo
6,El servicio al cliente fue poco profesional y ...,0,1,0.000000,0.000000,Neutro
7,"Me siento decepcionado, la calidad no es como ...",0,1,-0.750000,0.750000,Negativo
8,Tardaron demasiado en responder y no soluciona...,0,1,-0.050000,0.400000,Negativo
9,"No recomendaría este servicio, tuve problemas ...",0,1,0.000000,0.000000,Neutro

In [23]:
print(type(comentarios['tb_polaridad'][0]))
print(comentarios['tb_polaridad'][0] > 0)
print(comentarios['tb_sentimiento'].value_counts())

<class 'numpy.float64'>
True
tb_sentimiento
Positivo    115
Negativo     67
Neutro       21
Name: count, dtype: int64

In [12]:
# VADER
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer as sia

analyzer = sia()
traductor = ggt(source='auto', target='en')

compound_scores = []
sentimiento_vader = []

for texto in comentarios['texto']:
    # 1. Traducir al inglés
    traduccion = traductor.translate(texto)
    
    # 2. Analizar con VADER
    scores = analyzer.polarity_scores(traduccion)
    compound = scores['compound']
    
    # 3. Clasificar con umbrales estándar de VADER
    if compound >= 0.05:
        etiqueta = "Positivo"
    elif compound <= -0.05:
        etiqueta = "Negativo"
    else:
        etiqueta = "Neutro"
    
    compound_scores.append(compound)
    sentimiento_vader.append(etiqueta)

comentarios['vader_compound']    = compound_scores
comentarios['vader_sentimiento'] = sentimiento_vader

print(comentarios['vader_sentimiento'].value_counts())

vader_sentimiento
Positivo    106
Negativo     81
Neutro       16
Name: count, dtype: int64

In [5]:
import spacy
nlp = spacy.load("es_core_news_sm")

polaridad_sp = []
subjetividad_sp = []
sentimiento_sp = []

for texto in comentarios["texto"]:
    # 
    doc = nlp(texto)

    lemma = " ".join([token.lemma_ for token in doc
                        if not token.is_stop and not token.is_punct])

    blob = TextBlob(lemma)
    pol = blob.sentiment.polarity
    sub = blob.sentiment.subjectivity

    if pol > 0:
        etiqueta = "Positivo"
    elif pol < 0:
        etiqueta = "Negativo"
    else:
        etiqueta = "Neutro"

    
    polaridad_sp.append(pol)
    subjetividad_sp.append(sub)
    sentimiento_sp.append(etiqueta)

comentarios["spacy_polaridad"] = polaridad_sp
comentarios["spacy_subjetividad"] = subjetividad_sp
comentarios["spacy_sentimiento"] = sentimiento_sp

print(comentarios['spacy_sentimiento'].value_counts())

c:\Users\LENOVO\anaconda3\envs\sentiment_analysis\Lib\site-packages\spacy\util.py:971: UserWarning: [W095] Model 'es_core_news_sm' (3.7.0) was trained with spaCy v3.7.0 and may not be 100% compatible with the current version (3.8.14). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)

spacy_sentimiento
Neutro      178
Positivo     23
Negativo      2
Name: count, dtype: int64

In [ ]:

import time

clasificador = pipeline(
    "sentiment-analysis",
    model="nlptown/bert-base-multilingual-uncased-sentiment"
)

config.json:   0%|          | 0.00/953 [00:00<?, ?B/s]

c:\Users\LENOVO\anaconda3\envs\sentiment_analysis\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\LENOVO\.cache\huggingface\hub\models--nlptown--bert-base-multilingual-uncased-sentiment. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

model.safetensors:   0%|          | 0.00/669M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Device set to use cpu

In [7]:
inicio = time.time()
resultado = clasificador(comentarios['texto'][0])
fin = time.time()

print(resultado)
print(f"Tiempo por frase {fin - inicio:.2f} segundos")

[{'label': '5 stars', 'score': 0.7042403221130371}]
Tiempo por frase 0.27 segundos

In [24]:
puntuaciones = []
estrellas = []
seguridad_modelo = []

for texto in comentarios["texto"]:
    resultado = clasificador(texto)[0]
    label = resultado['label']
    stars = int(label[0])
    score = resultado['score']

    if stars <= 2:
        puntuacion = "Negativo"
    elif stars == 3:
        puntuacion = "Neutro"
    else:
        puntuacion = "Positivo"

puntuaciones.append(puntuacion)
estrellas.append(stars)
seguridad_modelo.append(score)

print(comentarios.value_counts())
#comentarios["Puntuación"] = puntuaciones
#comentarios["Estrellas"] = estrellas
#comentarios["seguridad_modelo"] = seguridad_modelo

    #print(f"Resultado: {resultado}")
    #print(f"Frase: {texto}")
    #print(f"Estrellas: {stars}")
    #print(f"Puntuacion: {puntuacion}")
    #print()

texto                                                                                                                                                    sentimiento  categoria  tb_polaridad   tb_subjetividad  tb_sentimiento
La exposición de arte moderno en el museo fue maravillosa, cada obra estaba llena de vida y creatividad, un deleite para los amantes del arte.           1            2           5.166667e-01  0.616667         Positivo          2
El concierto de la orquesta sinfónica fue una experiencia impresionante, cada pieza interpretada con una pasión que llegaba al alma, lo disfruté mucho.  1            2           5.866667e-01  0.653333         Positivo          2
La festividad cultural de este año fue realmente asombrosa, las tradiciones, bailes y muestras gastronómicas representaron fielmente nuestra herencia.   1            2           3.500000e-01  0.500000         Positivo          2
El documental que vi sobre las antiguas civilizaciones fue fascinante, muy bien investigado y con imágenes impactantes, muy recomendable.                1            2           3.120000e-01  0.538000         Positivo          2
La visita guiada al sitio arqueológico fue educativa y emocionante, el guía explicaba cada detalle con gran entusiasmo y conocimiento.                   1            2           3.375000e-01  0.450000         Positivo          2
                                                                                                                                                                                                                                  ..
El documental que vi sobre la historia del arte fue aburrido y no aportó nada nuevo al tema.                                                             0            2          -2.575758e-01  0.446970         Negativo          1
La visita al museo fue frustrante, muchas exhibiciones estaban cerradas y no había información suficiente.                                               0            2          -6.938894e-18  0.500000         Negativo          1
Los talleres extracurriculares han fomentado el desarrollo de habilidades prácticas y creativas en los estudiantes, complementando su educación formal.  1            3           5.000000e-01  1.000000         Positivo          1
La integración de tecnología en el aula ha facilitado la colaboración entre estudiantes, promoviendo un aprendizaje más dinámico y participativo.        1            3           2.500000e-01  0.333333         Positivo          1
Los programas de intercambio estudiantil han ampliado los horizontes culturales de los alumnos, enriqueciendo su formación personal y académica.         1            3           3.333333e-02  0.133333         Positivo          1
Name: count, Length: 191, dtype: int64

## Bibliografía:
1. https://huggingface.co/blog/sentiment-analysis-python
2.  
3.